In [1]:
import numpy as np

In [1]:
#Matrix 1D
mat1D = np.array([1,2,3,4,5,6,7,8,9,10])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

NameError: name 'np' is not defined

In [10]:
print(mat1D)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
print(mat1D[0])

1


In [14]:
print(mat1D + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [16]:
print(mat2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(mat2D[0])
print(mat2D[1])
print(mat2D[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [20]:
print(mat2D[0][2])

3


In [22]:
print(mat2D * 10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [28]:
print(mat1D.shape)
print(mat2D.shape)

(10,)
(3, 3)


In [30]:
print(mat1D.size)
print(mat2D.size)

10
9


In [56]:
#Special Matrix
mZero = np.zeros((3,3))
mIdentity = np.eye((4))
mFull = np.full((4,4),7)
mOne = np.ones((5,4))
mRandomFloat = np.random.rand(5,5)
mRandomInt = np.random.randint(10,101, size=6)

In [60]:
print(mZero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [46]:
print(mIdentity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
print(mOne)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [54]:
print(mRandomFloat)

[[0.33198426 0.51833453 0.24788356 0.34099243 0.58816103]
 [0.65397982 0.58695318 0.67998987 0.56147855 0.13728156]
 [0.21663125 0.57738197 0.9195715  0.14403287 0.91319211]
 [0.44461289 0.20754509 0.87321708 0.44716503 0.34354466]
 [0.20130363 0.23415735 0.40681367 0.5778471  0.74612451]]


In [58]:
print(mRandomInt)

[ 20 100  33  47  28  99]


In [82]:
x = np.array([2,6,9])
y = np.array([1,3,5])

dotProduct = np.dot(x,y)
addMatrix = np.add(x,y)
minValue = np.min(x)
maxValue = np.max(y)
meanValue = np.mean(y)
medianValue = np.median(y)
stdValue = np.std(y)
print(f"Hasil dari dot Product :{dotProduct}")
print(f"Hasil dari Penjumlahan Matriks :{addMatrix}")
print(f"Nilai minimum dari {x} : {minValue}")
print(f"Nilai maksimum dari {y}:{maxValue}")
print(f"Rata-rata Nilai dari {y}:{meanValue}")
print(f"Nilai median dari {y}:{medianValue}") 
print(f"Nilai Deviasi dari {y} : {stdValue}")

Hasil dari dot Product :65
Hasil dari Penjumlahan Matriks :[ 3  9 14]
Nilai minimum dari [2 6 9] : 2
Nilai maksimum dari [1 3 5]:5
Rata-rata Nilai dari [1 3 5]:3.0
Nilai median dari [1 3 5]:3.0
Nilai Deviasi dari [1 3 5] : 1.632993161855452


In [86]:
myArray = np.array([[1,2,3],[4,5,6]])

reshape = myArray.reshape(3,2)
flatten = myArray.flatten()

print(reshape)
print(flatten)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [88]:
#Filtering
nilaiSiswa = np.array([80,90,60,50,50,100,95])
lulus = nilaiSiswa[nilaiSiswa > 50]
jumlah = lulus.size
print(lulus)
print(f"Jumlah Siswa yang lulus:{jumlah}")

[ 80  90  60 100  95]
Jumlah Siswa yang lulus:5
